"""initial schema with 14 tables

Revision ID: 0ee61d902617
Revises: 
Create Date: 2026-04-01 21:40:25.767324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ee61d902617'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('old_state', sa.String(length=32), nullable=True),
    sa.Column('new_state', sa.String(length=32), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_audit_logs_project_id_action_created_at', 'audit_logs', ['project_id', 'action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_task_id_created_at', 'audit_logs', ['task_id', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('style_bible', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('category_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('rule_level', sa.String(length=16), nullable=False),
    sa.Column('rule_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index('ix_category_rules_project_id_category_is_active', 'category_rules', ['project_id', 'category', 'is_active'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('requester', sa.String(length=128), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('semantic_scene', sa.String(length=64), nullable=False),
    sa.Column('play_mode', sa.String(length=16), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_project_id_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_index('ix_tasks_requester', 'tasks', ['requester'], unique=False)
    op.create_table('wwise_templates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('template_type', sa.String(length=32), nullable=False),
    sa.Column('template_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('audio_intent_specs',
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('semantic_role', sa.String(length=64), nullable=True),
    sa.Column('intensity', sa.String(length=16), nullable=True),
    sa.Column('material_hint', sa.String(length=64), nullable=True),
    sa.Column('timing_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('loop_required', sa.Boolean(), nullable=False),
    sa.Column('variation_count', sa.SmallInteger(), nullable=False),
    sa.Column('design_pattern', sa.String(length=64), nullable=True),
    sa.Column('category_rule_id', sa.UUID(), nullable=True),
    sa.Column('wwise_template_id', sa.UUID(), nullable=True),
    sa.Column('ue_binding_strategy', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('unresolved_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['category_rule_id'], ['category_rules.rule_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['wwise_template_id'], ['wwise_templates.template_id'], ),
    sa.PrimaryKeyConstraint('intent_id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('binding_manifests',
    sa.Column('binding_manifest_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('bindings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unresolved_bindings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('binding_manifest_id')
    )
    op.create_index('ix_binding_manifests_task_id', 'binding_manifests', ['task_id'], unique=False)
    op.create_table('candidate_audios',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('source_model', sa.String(length=128), nullable=True),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index('ix_candidate_audios_task_id', 'candidate_audios', ['task_id'], unique=False)
    op.create_index('ix_candidate_audios_task_id_stage', 'candidate_audios', ['task_id', 'stage'], unique=False)
    op.create_table('input_asset_refs',
    sa.Column('input_asset_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('asset_kind', sa.String(length=32), nullable=False),
    sa.Column('asset_path', sa.String(length=1024), nullable=False),
    sa.Column('asset_version', sa.String(length=64), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('input_asset_id')
    )
    op.create_index('ix_input_asset_refs_task_id', 'input_asset_refs', ['task_id'], unique=False)
    op.create_table('qa_issues',
    sa.Column('qa_issue_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_sec', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('related_actor', sa.String(length=128), nullable=True),
    sa.Column('related_skill', sa.String(length=128), nullable=True),
    sa.Column('related_event', sa.String(length=256), nullable=True),
    sa.Column('root_cause_guess', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('qa_issue_id')
    )
    op.create_index('ix_qa_issues_project_id_issue_type', 'qa_issues', ['project_id', 'issue_type'], unique=False)
    op.create_index('ix_qa_issues_resolution_status', 'qa_issues', ['resolution_status'], unique=False)
    op.create_index('ix_qa_issues_task_id', 'qa_issues', ['task_id'], unique=False)
    op.create_table('review_records',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.String(length=32), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index('ix_review_records_task_id', 'review_records', ['task_id'], unique=False)
    op.create_table('rollback_points',
    sa.Column('rollback_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=32), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('rollback_id')
    )
    op.create_index('ix_rollback_points_task_id_created_at', 'rollback_points', ['task_id', 'created_at'], unique=False)
    op.create_table('wwise_object_manifests',
    sa.Column('manifest_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('object_entries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('import_status', sa.String(length=16), nullable=False),
    sa.Column('build_log', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('manifest_id')
    )
    op.create_index('ix_wwise_object_manifests_task_id', 'wwise_object_manifests', ['task_id'], unique=False)
    op.create_table('qc_reports',
    sa.Column('qc_report_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('peak_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loudness_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spectrum_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('head_tail_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('format_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qc_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_audios.candidate_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('qc_report_id')
    )
    op.create_index('ix_qc_reports_candidate_id', 'qc_reports', ['candidate_id'], unique=False)
    op.create_index('ix_qc_reports_task_id', 'qc_reports', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qc_reports_task_id', table_name='qc_reports')
    op.drop_index('ix_qc_reports_candidate_id', table_name='qc_reports')
    op.drop_table('qc_reports')
    op.drop_index('ix_wwise_object_manifests_task_id', table_name='wwise_object_manifests')
    op.drop_table('wwise_object_manifests')
    op.drop_index('ix_rollback_points_task_id_created_at', table_name='rollback_points')
    op.drop_table('rollback_points')
    op.drop_index('ix_review_records_task_id', table_name='review_records')
    op.drop_table('review_records')
    op.drop_index('ix_qa_issues_task_id', table_name='qa_issues')
    op.drop_index('ix_qa_issues_resolution_status', table_name='qa_issues')
    op.drop_index('ix_qa_issues_project_id_issue_type', table_name='qa_issues')
    op.drop_table('qa_issues')
    op.drop_index('ix_input_asset_refs_task_id', table_name='input_asset_refs')
    op.drop_table('input_asset_refs')
    op.drop_index('ix_candidate_audios_task_id_stage', table_name='candidate_audios')
    op.drop_index('ix_candidate_audios_task_id', table_name='candidate_audios')
    op.drop_table('candidate_audios')
    op.drop_index('ix_binding_manifests_task_id', table_name='binding_manifests')
    op.drop_table('binding_manifests')
    op.drop_table('audio_intent_specs')
    op.drop_table('wwise_templates')
    op.drop_index('ix_tasks_requester', table_name='tasks')
    op.drop_index('ix_tasks_project_id_status', table_name='tasks')
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_category_rules_project_id_category_is_active', table_name='category_rules')
    op.drop_table('category_rules')
    op.drop_table('projects')
    op.drop_index('ix_audit_logs_task_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_project_id_action_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
