"""add mapping_dictionaries table

Revision ID: 42a5ce1e63f6
Revises: 8f55a7fd4afe
Create Date: 2026-04-02 11:22:41.263048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42a5ce1e63f6'
down_revision: Union[str, Sequence[str], None] = '8f55a7fd4afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_dictionaries',
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('mapping_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_index('idx_mapping_project', 'mapping_dictionaries', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mapping_project', table_name='mapping_dictionaries')
    op.drop_table('mapping_dictionaries')
    # ### end Alembic commands ###
